language: node
node_js: 8.5
jobs:
  include:
    - stage: Frontend
      env:
      - a=b
      - BACKEND=http://127.0.0.1.xip.io:3000
      - FRONTEND=http://localhost:8081
      script:
      - echo $a
      - echo ${a}
      - node -v
      - cd frontend
      - npm i
      - npm run build
    - stage: Backend 
      script:
      - node -v
      - cd backend
      - npm i    
cache:
  directories:
    - node_modules