language: node
node_js: 8.5
env:
  - a=b
  - BACKEND=http://127.0.0.1.xip.io:3000
  - FRONTEND=http://localhost:8081
  - PORT=8081
jobs:
  include:
    - stage: test
      script:
      - echo $a
      - echo ${a}
      - node -v
      - cd frontend
      - npm i
      - npm run build
    - stage: test 
      script:
      - node -v
      - cd backend
      - npm i
    - stage: after-test
      script: echo "after-test"
cache:
  directories:
    - node_modules